spring:
  application:
    name: reading-writing-instance
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_write?characterEncoding=utf8&useSSL=true
    username: root
    password: 123123
  slaves:
    - driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test_read?characterEncoding=utf8&useSSL=true
      username: root
      password: 123123
    - driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=true
      username: root
      password: 123123
    - driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=true
      username: root
      password: 123123



mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.mapper
  configuration:
    call-setters-on-nulls: true


logging:
  level:
    root: INFO
